name: Build, SAST & Deploy React to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Notify Discord when build starts
      - name: Notify Discord (Build Started)
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"username\": \"CI/CD Bot\", \"embeds\": [{\"title\": \"🚀 Build Started\",\"color\": 3447003,\"fields\":[{\"name\":\"Repository\",\"value\":\"${{ github.repository }}\"},{\"name\":\"Branch\",\"value\":\"${{ github.ref_name }}\"},{\"name\":\"Workflow Run\",\"value\":\"[View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\"}]}]}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      # 4. Install dependencies
      - name: Install dependencies
        run: npm install

      # 5. Build React app
      - name: Build React app
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build

      # 6. Install Semgrep CLI
      - name: Install Semgrep CLI
        run: pip install semgrep

      # 7. Run Semgrep CI and upload results instantly
      - name: Run Semgrep CI
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        run: |
          RESULTS_FILE="$GITHUB_WORKSPACE/semgrep-results.json"

          semgrep ci \
            --config https://semgrep.dev/p/javascript \
            --config https://semgrep.dev/p/react \
            --config https://semgrep.dev/p/security-audit \
            --project 4130791 \
            --json \
            --output "$RESULTS_FILE" \
            || true

      # 8. Notify Discord with Semgrep results
      - name: Notify Discord (Semgrep Results)
        if: always()
        run: |
          RESULTS_FILE="$GITHUB_WORKSPACE/semgrep-results.json"

          if [ ! -f "$RESULTS_FILE" ]; then
            echo "Semgrep results file not found, skipping notification."
            exit 0
          fi

          findings=$(jq '.results | length' "$RESULTS_FILE" 2>/dev/null || echo 0)
          rules=$(jq '[.results[].check_id] | unique | length' "$RESULTS_FILE" 2>/dev/null || echo 0)
          total_files=$(git ls-files | wc -l)
          languages=$(jq -r '[.results[].extra.language] | map(select(.!=null)) | unique | join(", ")' "$RESULTS_FILE" 2>/dev/null || echo "N/A")

          summary="No issues found"
          color=3066993
          if [ "$findings" -gt 0 ]; then
            summary="$findings issue(s) found"
            color=15158332
          fi

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"username\": \"CI/CD Bot\",
              \"embeds\": [{
                \"title\": \"Semgrep Scan Report\",
                \"color\": $color,
                \"fields\": [
                  {\"name\":\"Repository\",\"value\":\"${{ github.repository }}\"},
                  {\"name\":\"Branch\",\"value\":\"${{ github.ref_name }}\"},
                  {\"name\":\"Rules Triggered\",\"value\":\"$rules\"},
                  {\"name\":\"Total Files Scanned\",\"value\":\"$total_files\"},
                  {\"name\":\"Languages Scanned\",\"value\":\"$languages\"},
                  {\"name\":\"Findings\",\"value\":\"$findings\"},
                  {\"name\":\"Summary\",\"value\":\"$summary\"},
                  {\"name\":\"Workflow Run\",\"value\":\"[View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\"}
                ]
              }]
            }" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      # 9. Deploy to Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        id: deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory: ./build

      # 10. Notify Discord on deployment success
      - name: Notify Discord (Deployment Success)
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"username\": \"CI/CD Bot\", \"embeds\": [{\"title\": \"✅ Deployment Successful\",\"color\": 3066993,\"fields\":[{\"name\":\"Repository\",\"value\":\"${{ github.repository }}\"},{\"name\":\"Branch\",\"value\":\"${{ github.ref_name }}\"},{\"name\":\"Workflow Run\",\"value\":\"[View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\"}]}]}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      # 11. Notify Discord on deployment failure
      - name: Notify Discord (Deployment Failed)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"username\": \"CI/CD Bot\", \"embeds\": [{\"title\": \"❌ Deployment Failed\",\"color\": 15158332,\"fields\":[{\"name\":\"Repository\",\"value\":\"${{ github.repository }}\"},{\"name\":\"Branch\",\"value\":\"${{ github.ref_name }}\"},{\"name\":\"Workflow Run\",\"value\":\"[View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\"}]}]}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
