name: Build & Deploy React to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      # Step 3: Install dependencies including ESLint security plugin
      - name: Install dependencies
        run: |
          npm install eslint@latest eslint-plugin-security --save-dev
          npm install

      # Step 4: Run ESLint with security plugin
      - name: Run ESLint
        run: npx eslint ./src --ext .js,.jsx || true

      # Step 5: Run npm audit
      - name: Run npm audit
        run: npm audit --audit-level=high || true

      # Step 6: Build the React app
      - name: Build React app
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build

      # Step 7: Deploy build to Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory: ./build
