name: Build, Scan & Deploy React to Cloudflare Pages
on:
  push:
    branches: [ main ]

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    outputs:
      scan-status: ${{ steps.set-status.outputs.status }}
      semgrep-color: ${{ steps.set-status.outputs.color }}
    steps:
      - uses: actions/checkout@v3

      - name: Install Semgrep CLI
        run: |
          curl -sSL https://github.com/returntocorp/semgrep/releases/download/v1.46.0/semgrep-linux-amd64-v1.46.0 -o semgrep
          chmod +x semgrep
          sudo mv semgrep /usr/local/bin/

      - name: Run Semgrep scan
        run: semgrep scan --config auto --json > semgrep-report.json || true

      - name: Extract Semgrep summary
        run: |
          if [ -s semgrep-report.json ]; then
            jq -r '.results[] | "- \(.check_id): \(.path):\(.start.line) - \(.extra.message) [Severity: \(.extra.severity)]"' semgrep-report.json > semgrep-summary.txt
            HIGH_SEV=$(jq '.results[] | select(.extra.severity=="ERROR")' semgrep-report.json)
            if [ -n "$HIGH_SEV" ]; then COLOR=15158332; else COLOR=3066993; fi
          else
            echo "✅ No issues found" > semgrep-summary.txt
            COLOR=3066993
          fi
          echo "status=completed" >> $GITHUB_OUTPUT
          echo "color=$COLOR" >> $GITHUB_OUTPUT
        id: set-status

      - uses: actions/upload-artifact@v4
        with:
          name: semgrep-summary
          path: semgrep-summary.txt

  build:
    runs-on: ubuntu-latest
    needs: semgrep-scan
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build
          path: ./build
      - uses: actions/download-artifact@v4
        with:
          name: semgrep-summary
      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory: ./build
      - name: Prepare Discord variables
        run: |
          SUMMARY=$(awk '{printf "%s\n", $0}' semgrep-summary.txt)
          NOW=$(date +"%Y-%m-%d %H:%M:%S %Z")
          echo "SEMGRP_SUMMARY<<EOF" >> $GITHUB_ENV
          echo "$SUMMARY" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          echo "RUN_DATETIME=$NOW" >> $GITHUB_ENV
          echo "COMMIT_URL=https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}" >> $GITHUB_ENV

      - uses: rjstone/discord-webhook-notify@v2.2.1
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "🚀 Build & Deploy Report"
          description: |
            **Branch**: `${{ github.ref_name }}`
            **Commit**: [${{ github.sha }}](${{ env.COMMIT_URL }})
            **Semgrep Status**: `${{ needs.semgrep-scan.outputs.scan-status }}`
            **Deploy Status**: `${{ job.status }}`
            **Date/Time**: `${{ env.RUN_DATETIME }}`
          text: |
            🔍 **Semgrep Findings**:
            ${{ env.SEMGRP_SUMMARY }}
          color: "${{ needs.semgrep-scan.outputs.semgrep-color }}"
