name: Build, Security Scan & Deploy React to Cloudflare Pages

on:
  push:
    branches:
      - main   # Trigger on main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24  # Latest Node LTS

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run ESLint security plugin separately (without changing CRA's ESLint)
      - name: Run ESLint Security Scan
        run: |
          npm install eslint-plugin-security --save-dev
          npx eslint --plugin security ./src --ext .js,.jsx || true

      # Step 5: Build React app (CRA)
      - name: Build React app
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build

      # Step 6: Deploy build to Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory: ./build
