name: Build, SAST & Deploy React to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Notify Discord when build starts
      - name: Notify Discord (Build Started)
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"username\": \"CI/CD Bot\", \"embeds\": [{\"title\": \"🚀 Build Started\",\"color\": 3447003,\"fields\":[{\"name\":\"Repository\",\"value\":\"${{ github.repository }}\"},{\"name\":\"Branch\",\"value\":\"${{ github.ref_name }}\"},{\"name\":\"Workflow Run\",\"value\":\"[View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\"}]}]}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build

      # Run Semgrep (Docker)
      - name: Run Semgrep SAST (Docker)
        run: |
          RESULTS_FILE="$GITHUB_WORKSPACE/semgrep-results.json"
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/src" \
            -e SEMGREP_NO_METRICS=1 \
            semgrep/semgrep:latest \
            semgrep scan \
              --config https://semgrep.dev/p/javascript \
              --config https://semgrep.dev/p/react \
              --config https://semgrep.dev/p/security-audit \
              --json \
              --output /src/semgrep-results.json || true

      # Debug Semgrep Output
      - name: Debug Semgrep Output
        run: |
          echo "Workspace contents:"
          ls -la $GITHUB_WORKSPACE
          echo "Semgrep results file:"
          ls -la $GITHUB_WORKSPACE/semgrep-results.json || echo "File not found"

      # Notify Discord with Semgrep Results
      - name: Notify Discord (Semgrep Results)
        if: always()
        run: |
          RESULTS_FILE="$GITHUB_WORKSPACE/semgrep-results.json"

          if [ ! -f "$RESULTS_FILE" ]; then
            echo "⚠️ Semgrep results file not found, skipping notification."
            exit 0
          fi

          findings=$(jq '.results | length' "$RESULTS_FILE" 2>/dev/null || echo 0)
          rules=$(jq '.scan.rules_count' "$RESULTS_FILE" 2>/dev/null || echo "N/A")
          targets=$(jq '.scan.targets_count' "$RESULTS_FILE" 2>/dev/null || echo "N/A")

          summary="No issues found"
          color=3066993
          if [ "$findings" -gt 0 ]; then
            summary="$findings issue(s) found"
            color=15158332
          fi

          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{
              \"username\": \"CI/CD Bot\",
              \"embeds\": [{
                \"title\": \"🛡 Semgrep Scan Report\",
                \"color\": $color,
                \"fields\": [
                  {\"name\":\"Repository\",\"value\":\"${{ github.repository }}\"},
                  {\"name\":\"Branch\",\"value\":\"${{ github.ref_name }}\"},
                  {\"name\":\"Rules Run\",\"value\":\"$rules\"},
                  {\"name\":\"Targets Scanned\",\"value\":\"$targets\"},
                  {\"name\":\"Findings\",\"value\":\"$findings\"},
                  {\"name\":\"Summary\",\"value\":\"$summary\"},
                  {\"name\":\"Workflow Run\",\"value\":\"[View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\"}
                ]
              }]
            }" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      # Deploy to Cloudflare Pages
      - name: Deploy to Cloudflare Pages
        id: deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory: ./build

      # Notify Discord on deployment success
      - name: Notify Discord (Deployment Success)
        if: success()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"username\": \"CI/CD Bot\", \"embeds\": [{\"title\": \"✅ Deployment Successful\",\"color\": 3066993,\"fields\":[{\"name\":\"Repository\",\"value\":\"${{ github.repository }}\"},{\"name\":\"Branch\",\"value\":\"${{ github.ref_name }}\"},{\"name\":\"Workflow Run\",\"value\":\"[View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\"}]}]}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}

      # Notify Discord on deployment failure
      - name: Notify Discord (Deployment Failed)
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"username\": \"CI/CD Bot\", \"embeds\": [{\"title\": \"❌ Deployment Failed\",\"color\": 15158332,\"fields\":[{\"name\":\"Repository\",\"value\":\"${{ github.repository }}\"},{\"name\":\"Branch\",\"value\":\"${{ github.ref_name }}\"},{\"name\":\"Workflow Run\",\"value\":\"[View Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})\"}]}]}" \
            ${{ secrets.DISCORD_WEBHOOK_URL }}
