name: Build, Scan & Deploy React to Cloudflare Pages

on:
  push:
    branches:
      - main

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Semgrep
        run: |
          curl -sSL https://github.com/returntocorp/semgrep/releases/download/v1.46.0/semgrep-linux-amd64-v1.46.0.tar.gz -o semgrep.tar.gz
          tar -xzf semgrep.tar.gz
          sudo mv semgrep /usr/local/bin/

      - name: Run Semgrep scan
        id: semgrep
        run: |
          semgrep --config p/ci --sarif > semgrep.sarif
        continue-on-error: true

      - name: Upload Semgrep results
        uses: actions/upload-artifact@v3
        with:
          name: semgrep-sarif
          path: semgrep.sarif

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: semgrep-scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: |
          export NODE_OPTIONS=--openssl-legacy-provider
          npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: ${{ secrets.CF_PROJECT_NAME }}
          directory: ./build

      - name: Notify Discord
        if: always()
        uses: Ilshidur/action-discord@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            🚀 **Build & Deploy Report**
            Branch: `${{ github.ref }}`
            Commit: `${{ github.sha }}`
            Semgrep Scan: `${{ needs.semgrep-scan.result }}`
            Build & Deploy: `${{ job.status }}`
